#ifndef SSO_DEHYDRATOR_EVS_H_
#define SSO_DEHYDRATOR_EVS_H_

#define SSO_DEHYD_INT_MAILIST(X) \
X(SSO_DEHYD_INT_SUNLIGHT_UPDATE_MID,  "") \
X(SSO_DEHYD_INT_TEMP_UPDATE_MID,      "") \
X(SSO_DEHYD_INT_DRIVERS_READY_MID,    "") \
X(SSO_DEHYD_INT_DARK_MODE_OP_MID,     "") \
X(SSO_DEHYD_INT_SUNLIGHT_MODE_OP_MID, "") \
X(SSO_DEHYD_INT_START_OP_MID,         "") \
X(SSO_DEHYD_INT_TIMER_UPDATE_MID,     "") \
X(SSO_DEHYD_INT_STOP_OP_MID,          "") \

#define SSO_DEHYD_PBC_MAILIST(X) \
X(SSO_DEHYD_PBC_START_OP, "") \
X(SSO_DEHYD_PBC_STOP_OP, "")

#endif /*SSO_DEHYDRATOR_EVS_H_*/