#ifndef SSO_DEHYDRATOR_USET_H_
#define SSO_DEHYDRATOR_USET_H_

#define SSO_DEHYDRATOR_MIN_TEMP (110000)
#define SSO_DEHYDRATOR_MAX_TEMP (118000)

#define SSO_DEHYDRATOR_MIN_SUNLIGHT (4500)
#define SSO_DEHYDRATOR_HYSTHERESIS  (500)

#endif /*SSO_DEHYDRATOR_USET_H_*/